version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: mdpi_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: jaffle_shop
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbt -d jaffle_shop"]
      interval: 5s
      timeout: 3s
      retries: 15

  # For explore the DB
  adminer:
    image: adminer:4
    container_name: mdpi_adminer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pg_data:
