[project]
name = "jaffle-shop-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core~=1.8",
    "dbt-postgres~=1.8",
    "psycopg[binary]>=3.1",
    "python-dotenv>=1.1.1",
]
