name: SQL Lint (SQLFluff)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install SQLFluff + dbt templater
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff>=3.0.0" sqlfluff-templater-dbt "dbt-core==1.9.0" "dbt-postgres==1.9.0"

      - name: Install dbt packages
        run: dbt deps

      - name: Lint models
        run: sqlfluff lint models
